/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  return knex("venues")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("venues").insert([
        {
          id: 1,
          name: "Luma",
          neighbourhood: "King West",
          address: "330 King St West, Toronto ON M5V 3X5",
          photo: "http://localhost:8080/images/photo-01.jpg",
          website: "http://www.lumarestaurant.com",
          description: "Luma offers a chic and modern dining experience with a focus on fresh, locally sourced ingredients. The stylish ambiance and floor-to-ceiling windows create the perfect setting for a sophisticated night out.",
          lat: 43.646546,
          lng: -79.390704,
        },
        {
          id: 2,
          name: "The Joneses",
          neighbourhood: "Downtown Toronto",
          address: "33 Yonge St #100, Toronto ON M5E 1S9",
          photo: "http://localhost:8080/images/photo-02.jpg",
          website: "",
          description:"A lively downtown hotspot, The Joneses boasts a sleek, contemporary design and a menu filled with elevated comfort food. With its upbeat vibe and craft cocktails, it's an ideal destination for after-work drinks or weekend socializing.",
          lat: 43.64762,
          lng: -79.37622,
        },
        {
          id: 3,
          name: "O&B Canteen",
          neighbourhood: "King West",
          address: "330 King St. W, Toronto ON M5V 3X2",
          photo: "http://localhost:8080/images/photo-03.jpg",
          website: "https://www.obcanteen.com",
          description:"A vibrant and casual eatery in the bustling King West district, O&B Canteen is known for its all-day menu and relaxed café-style atmosphere. Whether you're grabbing a quick bite or enjoying a leisurely meal, this spot offers a warm and welcoming setting.",
          lat: 43.646546,
          lng: -79.390704,
        },
        {
          id: 4,
          name: "The Dorset",
          neighbourhood: "Leslieville",
          address: "2190 Queen St E, Toronto ON M4E 1E2",
          photo: "http://localhost:8080/images/photo-04.jpg",
          website: "",
          description:"Nestled in the heart of Leslieville, The Dorset brings a touch of British charm to Toronto. This cozy pub offers hearty dishes, a great selection of pints, and a friendly, laid-back atmosphere that makes it a neighborhood favorite.",
          lat: 43.671982,
          lng: -79.288857,
        },
        {
          id: 5,
          name: "Valerie",
          neighbourhood: "Waterfront",
          address: "111 Princes' Blvd, Toronto ON M6K 3C3",
          photo: "http://localhost:8080/images/photo-05.jpg",
          website: "https://www.chotto-matte.com",
          description:"Overlooking Toronto’s waterfront, Valerie is an upscale lounge with stunning views and a refined cocktail menu. The elegant décor and intimate setting make it a great choice for date nights or sophisticated gatherings.",
          lat: 43.633819,
          lng: -79.4227,
        },
        {
          id: 6,
          name: "Cactus Club Cafe",
          neighbourhood: "Financial District",
          address: "77 Adelaide St W, Toronto ON M5X 1C1",
          photo: "http://localhost:8080/images/photo-06.jpg",
          website: "http://www.cactusclubcafe.com",
          description:"A sleek and stylish spot in the Financial District, offering globally inspired dishes and craft cocktails in a lively setting.",
          lat: 43.648873,
          lng: -79.381707,
        },
        {
          id: 7,
          name: "Chotto Matte",
          neighbourhood: "Downtown Toronto",
          address: "161 Bay St, Toronto ON M5J 2S4",
          photo: "http://localhost:8080/images/photo-07.jpg",
          website: "https://www.chotto-matte.com",
          description:"A vibrant fusion of Japanese and Peruvian flavors with bold decor and an energetic atmosphere in downtown Toronto.",
          lat: 43.64756,
          lng: -79.37897,
        },
        {
          id: 8,
          name: "Baro",
          neighbourhood: "King West",
          address: "485 King Street West, Toronto ON M5V 1K4",
          photo: "http://localhost:8080/images/photo-08.jpg",
          website: "http://www.barotoronto.com",
          description:"A trendy Latin American restaurant on King West, known for its flavorful share plates, rooftop patio, and lively vibe.",
          lat: 43.64412,
          lng: -79.39616,
        },
        {
          id: 9,
          name: "The Rec Room",
          neighbourhood: "Waterfront",
          address: "255 Bremner Blvd, Toronto ON M5V 3M9",
          photo: "http://localhost:8080/images/photo-09.jpg",
          website: "https://www.therecroom.com",
          description:"A massive entertainment hub by the waterfront, featuring arcade games, live music, and a full bar for a fun night out.",
          lat: 43.64128,
          lng: -79.38545,
        },
        {
          id: 10,
          name: "Scaddabush",
          neighbourhood: "Financial District",
          address: "156 Front St W, Toronto ON M5J 2L6",
          photo: "http://localhost:8080/images/photo-10.jpg",
          website: "https://www.scaddabush.com",
          description:"A cozy Italian eatery in the Financial District, serving fresh pasta, handmade mozzarella, and classic comfort dishes.",
          lat: 43.64476,
          lng: -79.38546,
        },
        {
          id: 11,
          name: "The Keg Steakhouse + Bar",
          neighbourhood: "Yorkville",
          address: "40 Front St E, Toronto ON M5E 1A1",
          photo: "http://localhost:8080/images/photo-11.jpg",
          website: "https://www.kegsteakhouse.com",
          description:"A classic steakhouse offering a variety of high-quality steaks, seafood, and delicious cocktails in a relaxed yet refined atmosphere. ",
          lat: 43.64705,
          lng: -79.37587,
        },
        {
          id: 12,
          name: "BarChef",
          neighbourhood: "Queen West",
          address: "472 Queen St W, Toronto ON M5V 2A9",
          photo: "http://localhost:8080/images/photo-12.jpg",
          website: "https://www.barchef.com",
          description:"A trendy cocktail bar known for its innovative drink creations, blending art and mixology with a stylish ambiance. Ideal for adventurous cocktail enthusiasts.",
          lat: 43.6473,
          lng: -79.3996,
        },
        {
          id: 13,
          name: "Kōjin",
          neighbourhood: "King Street West",
          address: "190 University Ave, Toronto ON M5H 0A3",
          photo: "http://localhost:8080/images/photo-13.jpg",
          website: "https://www.konrestaurant.com",
          description:"A modern dining experience with a focus on grilled meats and wood-fired cooking, offering a unique blend of flavors in a chic, contemporary setting.",
          lat: 43.64929,
          lng: -79.38653,
        },
        {
          id: 14,
          name: "Patria",
          neighbourhood: "King West",
          address: "478 King St W, Toronto ON M5V 1L7",
          photo: "http://localhost:8080/images/photo-14.jpg",
          website: "https://www.patria.ca",
          description:"A Spanish-inspired restaurant with an upscale atmosphere, serving traditional tapas, meats, and seafood with a modern twist. Ideal for sharing plates in a vibrant setting.",
          lat: 43.64415,
          lng: -79.396,
        },
        {
          id: 15,
          name: "The Drake Hotel",
          neighbourhood: "Queen West",
          address: "1150 Queen St W, Toronto ON M6J 1J3",
          photo: "http://localhost:8080/images/photo-15.jpg",
          website: "https://www.thedrake.ca",
          description:"A popular venue for both locals and tourists, offering a mix of trendy dining, live music, and a lively bar scene. Known for its eclectic vibe and creative cocktails.",
          lat: 43.6426,
          lng: -79.4222,
        },
        {
          id: 16,
          name: "The Queen & Beaver Public House",
          neighbourhood: "Yorkville",
          address: "35 Elm St, Toronto ON M5G 1H1",
          photo: "http://localhost:8080/images/photo-16.jpg",
          website: "https://www.queenandbeaver.ca",
          description:"A British-style pub offering hearty comfort food, classic ales, and a cozy atmosphere. A great spot for a casual meal or a pint with friends.",
          lat: 43.657313,
          lng: -79.38323,
        },
        {
          id: 17,
          name: "Wildfire Steakhouse & Wine Bar",
          neighbourhood: "Yorkville",
          address: "2300 Yonge St, Toronto ON M4P 1E4",
          photo: "http://localhost:8080/images/photo-17.jpg",
          website: "https://www.wildfiresteakhouse.com",
          description:"A sophisticated steakhouse with a wide selection of prime cuts, seafood, and an extensive wine list. Known for its exceptional service and upscale ambiance.",
          lat: 43.707069,
          lng: -79.39874,
        },
        {
          id: 18,
          name: "Richmond Station",
          neighbourhood: "Financial District",
          address: "1 Richmond St W, Toronto ON M5H 3W4",
          photo: "http://localhost:8080/images/photo-18.jpg",
          website: "https://richmondstation.ca",
          description:"A modern restaurant with seasonal dishes and an open kitchen. The vibe is lively yet refined, perfect for a casual yet stylish dining experience.",
          lat: 43.65107,
          lng: -79.347015,
        },
        {
          id: 19,
          name: "The Miller Tavern",
          neighbourhood: "York Mills",
          address: "3885 Yonge St, Toronto ON M4N 3N6",
          photo: "http://localhost:8080/images/photo-19.jpg",
          website: "https://millerstaverntoronto.ca",
          description:"A cozy Canadian tavern serving comfort food and seafood. The atmosphere is warm, rustic, and laid-back, ideal for a relaxed meal.",
          lat: 43.737564,
          lng: -79.405747,
        },
        {
          id: 20,
          name: "Bar Reyna",
          neighbourhood: "Yorkville",
          address: "158 Cumberland St, Toronto ON M5R 1A8",
          photo: "http://localhost:8080/images/photo-20.jpg",
          website: "https://barreyna.com",
          description:"A chic Mediterranean restaurant and cocktail bar with a vibrant atmosphere, stylish décor, and fresh tapas.",
          lat: 43.670876,
          lng: -79.393398,
        },
        {
          id: 21,
          name: "The Saint Tavern",
          neighbourhood: "Queen West",
          address: "286 King St W, Toronto ON M5V 1J2",
          photo: "http://localhost:8080/images/photo-21.jpg",
          website: "https://thesainttavern.com",
          description:"A casual neighborhood tavern with classic pub fare and a cozy, vintage-inspired atmosphere, perfect for a laid-back evening.",
          lat: 43.646547,
          lng: -79.390564,
        },
        {
          id: 22,
          name: "Taverna Mercatto",
          neighbourhood: "King Street West",
          address: "225 King St W, Toronto ON M5V 3M2",
          photo: "http://localhost:8080/images/photo-22.jpg",
          website: "https://mercatto.ca",
          description:"A lively Italian eatery offering rustic dishes in a warm, inviting space with an energetic vibe.",
          lat: 43.646973,
          lng: -79.386707,
        },
        {
          id: 23,
          name: "Café Boulud",
          neighbourhood: "Yorkville",
          address: "60 Yorkville Ave, Toronto ON M4W 0A4",
          photo: "http://localhost:8080/images/photo-23.jpg",
          website: "https://www.cafeboulud.com",
          description:"An elegant French bistro with a sophisticated atmosphere, perfect for special occasions or a refined night out.",
          lat: 43.670201,
          lng: -79.388703,
        },
        {
          id: 24,
          name: "Kinka Izakaya Original",
          neighbourhood: "Financial District",
          address: "398 Church St, Toronto ON M5B 2A2",
          photo: "http://localhost:8080/images/photo-24.jpg",
          website: "https://kinka.com",
          description:"A lively Japanese izakaya with small plates and a casual, energetic atmosphere, ideal for group dining.",
          lat: 43.661228,
          lng: -79.378537,
        },
        {
          id: 25,
          name: "Tutto Pronto",
          neighbourhood: "Dundas West",
          address: "1175 Dundas St W, Toronto ON M6J 1X4",
          photo: "http://localhost:8080/images/photo-25.jpg",
          website: "https://www.tuttopronto.com",
          description:"A cozy Italian restaurant serving homemade pasta and pizza in a casual, rustic setting.",
          lat: 43.649154,
          lng: -79.424928,
        },
      ]);
    });
}
