/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export function seed(knex) {
    // Deletes ALL existing entries
    return knex('deals').del()
      .then(function () {
        // Inserts seed entries
        return knex('deals').insert([
          // Luma Deals
          { venue_id: 1, type_of_drink: 'cocktail', category: 'Signature Cocktail', price: 6, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 1, type_of_drink: 'cocktail', category: 'Signature Cocktail', price: 6, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 1, type_of_drink: 'cocktail', category: 'Signature Cocktail', price: 6, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 1, type_of_drink: 'cocktail', category: 'Signature Cocktail', price: 6, start: '16:00', end: '17:30', day: 'Friday' },
          { venue_id: 1, type_of_drink: 'cocktail', category: 'Signature Cocktail', price: 6, start: '16:00', end: '17:30', day: 'Saturday' },
          { venue_id: 1, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Tuesday' },
          { venue_id: 1, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Wednesday' },
          { venue_id: 1, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Thursday' },
          { venue_id: 1, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Friday' },
          { venue_id: 1, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Saturday' },
          { venue_id: 1, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 1, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 1, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 1, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Friday' },
          { venue_id: 1, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Saturday' },
          { venue_id: 1, type_of_food: 'main', category: 'Calamari', price: 10, start: '17:30', end: '20:00', day: 'Tuesday' },
          { venue_id: 1, type_of_food: 'main', category: 'Calamari', price: 10, start: '17:30', end: '20:00', day: 'Wednesday' },
          { venue_id: 1, type_of_food: 'main', category: 'Calamari', price: 10, start: '17:30', end: '20:00', day: 'Thursday' },
          { venue_id: 1, type_of_food: 'main', category: 'Calamari', price: 10, start: '17:30', end: '20:00', day: 'Friday' },
          { venue_id: 1, type_of_food: 'main', category: 'Calamari', price: 10, start: '17:30', end: '20:00', day: 'Saturday' },
  
          // The Joneses Deals
          { venue_id: 2, type_of_drink: 'cocktail', category: 'House Margarita', price: 5, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 2, type_of_drink: 'cocktail', category: 'House Margarita', price: 5, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 2, type_of_drink: 'cocktail', category: 'House Margarita', price: 5, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 2, type_of_drink: 'cocktail', category: 'House Margarita', price: 5, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 2, type_of_drink: 'cocktail', category: 'House Margarita', price: 5, start: '17:00', end: '18:00', day: 'Saturday' },
          { venue_id: 2, type_of_drink: 'beer', category: 'Beer (local tap)', price: 4, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 2, type_of_drink: 'beer', category: 'Beer (local tap)', price: 4, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 2, type_of_drink: 'beer', category: 'Beer (local tap)', price: 4, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 2, type_of_drink: 'beer', category: 'Beer (local tap)', price: 4, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 2, type_of_drink: 'beer', category: 'Beer (local tap)', price: 4, start: '17:00', end: '18:00', day: 'Saturday' },
          { venue_id: 2, type_of_food: 'main', category: 'Tacos', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 2, type_of_food: 'main', category: 'Tacos', price: 6, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 2, type_of_food: 'main', category: 'Tacos', price: 6, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 2, type_of_food: 'main', category: 'Tacos', price: 6, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 2, type_of_food: 'main', category: 'Tacos', price: 6, start: '17:00', end: '18:00', day: 'Saturday' },
          { venue_id: 2, type_of_food: 'appetizer', category: 'Wings', price: 8, start: '18:00', end: '19:00', day: 'Tuesday' },
          { venue_id: 2, type_of_food: 'appetizer', category: 'Wings', price: 8, start: '18:00', end: '19:00', day: 'Wednesday' },
          { venue_id: 2, type_of_food: 'appetizer', category: 'Wings', price: 8, start: '18:00', end: '19:00', day: 'Thursday' },
          { venue_id: 2, type_of_food: 'appetizer', category: 'Wings', price: 8, start: '18:00', end: '19:00', day: 'Friday' },
          { venue_id: 2, type_of_food: 'appetizer', category: 'Wings', price: 8, start: '18:00', end: '19:00', day: 'Saturday' },
  
          // O&B Canteen Deals
          { venue_id: 3, type_of_drink: 'cocktail', category: 'Cosmopolitan', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
          { venue_id: 3, type_of_drink: 'cocktail', category: 'Cosmopolitan', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 3, type_of_drink: 'cocktail', category: 'Cosmopolitan', price: 7, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 3, type_of_drink: 'cocktail', category: 'Cosmopolitan', price: 7, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 3, type_of_drink: 'cocktail', category: 'Cosmopolitan', price: 7, start: '16:00', end: '17:30', day: 'Friday' },
          { venue_id: 3, type_of_drink: 'beer', category: 'Pale Ale', price: 4, start: '16:00', end: '17:30', day: 'Monday' },
          { venue_id: 3, type_of_drink: 'beer', category: 'Pale Ale', price: 4, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 3, type_of_drink: 'beer', category: 'Pale Ale', price: 4, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 3, type_of_drink: 'beer', category: 'Pale Ale', price: 4, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 3, type_of_drink: 'beer', category: 'Pale Ale', price: 4, start: '16:00', end: '17:30', day: 'Friday' },
          { venue_id: 3, type_of_food: 'appetizer', category: 'Chips & Guacamole', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
          { venue_id: 3, type_of_food: 'appetizer', category: 'Chips & Guacamole', price: 6, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 3, type_of_food: 'appetizer', category: 'Chips & Guacamole', price: 6, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 3, type_of_food: 'appetizer', category: 'Chips & Guacamole', price: 6, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 3, type_of_food: 'appetizer', category: 'Chips & Guacamole', price: 6, start: '16:00', end: '17:30', day: 'Friday' },
  
          // The Dorset Deals
          { venue_id: 4, type_of_drink: 'cocktail', category: 'Negroni', price: 8, start: '16:00', end: '17:30', day: 'Tuesday' },
          { venue_id: 4, type_of_drink: 'cocktail', category: 'Negroni', price: 8, start: '16:00', end: '17:30', day: 'Wednesday' },
          { venue_id: 4, type_of_drink: 'cocktail', category: 'Negroni', price: 8, start: '16:00', end: '17:30', day: 'Thursday' },
          { venue_id: 4, type_of_drink: 'cocktail', category: 'Negroni', price: 8, start: '16:00', end: '17:30', day: 'Friday' },
          { venue_id: 4, type_of_drink: 'cocktail', category: 'Negroni', price: 8, start: '16:00', end: '17:30', day: 'Saturday' },
        
           // Valerie Deals
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Classic Mojito', price: 6, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Classic Mojito', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Classic Mojito', price: 6, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Classic Mojito', price: 6, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Classic Mojito', price: 6, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Champagne Cocktail', price: 8, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Champagne Cocktail', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Champagne Cocktail', price: 8, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Champagne Cocktail', price: 8, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 5, type_of_drink: 'cocktail', category: 'Champagne Cocktail', price: 8, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Shrimp Tempura', price: 10, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Shrimp Tempura', price: 10, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Shrimp Tempura', price: 10, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Shrimp Tempura', price: 10, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Shrimp Tempura', price: 10, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Tuna Lettuce Wraps', price: 8, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Tuna Lettuce Wraps', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Tuna Lettuce Wraps', price: 8, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Tuna Lettuce Wraps', price: 8, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 5, type_of_food: 'appetizer', category: 'Tuna Lettuce Wraps', price: 8, start: '17:00', end: '18:00', day: 'Friday' },
   
           // Cactus Club Cafe Deals
           { venue_id: 6, type_of_drink: 'cocktail', category: 'Cactus Club Margarita', price: 7, start: '15:00', end: '16:00', day: 'Monday' },
           { venue_id: 6, type_of_drink: 'cocktail', category: 'Cactus Club Margarita', price: 7, start: '15:00', end: '16:00', day: 'Tuesday' },
           { venue_id: 6, type_of_drink: 'cocktail', category: 'Cactus Club Margarita', price: 7, start: '15:00', end: '16:00', day: 'Wednesday' },
           { venue_id: 6, type_of_drink: 'cocktail', category: 'Cactus Club Margarita', price: 7, start: '15:00', end: '16:00', day: 'Thursday' },
           { venue_id: 6, type_of_drink: 'cocktail', category: 'Cactus Club Margarita', price: 7, start: '15:00', end: '16:00', day: 'Friday' },
           { venue_id: 6, type_of_drink: 'beer', category: 'House Beer', price: 4, start: '15:00', end: '16:00', day: 'Monday' },
           { venue_id: 6, type_of_drink: 'beer', category: 'House Beer', price: 4, start: '15:00', end: '16:00', day: 'Tuesday' },
           { venue_id: 6, type_of_drink: 'beer', category: 'House Beer', price: 4, start: '15:00', end: '16:00', day: 'Wednesday' },
           { venue_id: 6, type_of_drink: 'beer', category: 'House Beer', price: 4, start: '15:00', end: '16:00', day: 'Thursday' },
           { venue_id: 6, type_of_drink: 'beer', category: 'House Beer', price: 4, start: '15:00', end: '16:00', day: 'Friday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Spicy Tuna Tacos', price: 6, start: '15:00', end: '16:00', day: 'Monday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Spicy Tuna Tacos', price: 6, start: '15:00', end: '16:00', day: 'Tuesday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Spicy Tuna Tacos', price: 6, start: '15:00', end: '16:00', day: 'Wednesday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Spicy Tuna Tacos', price: 6, start: '15:00', end: '16:00', day: 'Thursday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Spicy Tuna Tacos', price: 6, start: '15:00', end: '16:00', day: 'Friday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Crispy Calamari', price: 9, start: '15:00', end: '16:00', day: 'Monday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Crispy Calamari', price: 9, start: '15:00', end: '16:00', day: 'Tuesday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Crispy Calamari', price: 9, start: '15:00', end: '16:00', day: 'Wednesday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Crispy Calamari', price: 9, start: '15:00', end: '16:00', day: 'Thursday' },
           { venue_id: 6, type_of_food: 'appetizer', category: 'Crispy Calamari', price: 9, start: '15:00', end: '16:00', day: 'Friday' },
         
           // Chotto Matte Deals
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Sake Mule', price: 5, start: '15:00', end: '16:00', day: 'Monday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Sake Mule', price: 5, start: '15:00', end: '16:00', day: 'Tuesday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Sake Mule', price: 5, start: '15:00', end: '16:00', day: 'Wednesday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Sake Mule', price: 5, start: '15:00', end: '16:00', day: 'Thursday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Sake Mule', price: 5, start: '15:00', end: '16:00', day: 'Friday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Japanese Whisky Highball', price: 7, start: '15:00', end: '16:00', day: 'Monday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Japanese Whisky Highball', price: 7, start: '15:00', end: '16:00', day: 'Tuesday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Japanese Whisky Highball', price: 7, start: '15:00', end: '16:00', day: 'Wednesday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Japanese Whisky Highball', price: 7, start: '15:00', end: '16:00', day: 'Thursday' },
         { venue_id: 7, type_of_drink: 'cocktail', category: 'Japanese Whisky Highball', price: 7, start: '15:00', end: '16:00', day: 'Friday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Edamame', price: 4, start: '15:00', end: '16:00', day: 'Monday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Edamame', price: 4, start: '15:00', end: '16:00', day: 'Tuesday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Edamame', price: 4, start: '15:00', end: '16:00', day: 'Wednesday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Edamame', price: 4, start: '15:00', end: '16:00', day: 'Thursday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Edamame', price: 4, start: '15:00', end: '16:00', day: 'Friday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Tuna Poke', price: 8, start: '15:00', end: '16:00', day: 'Monday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Tuna Poke', price: 8, start: '15:00', end: '16:00', day: 'Tuesday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Tuna Poke', price: 8, start: '15:00', end: '16:00', day: 'Wednesday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Tuna Poke', price: 8, start: '15:00', end: '16:00', day: 'Thursday' },
         { venue_id: 7, type_of_food: 'appetizer', category: 'Tuna Poke', price: 8, start: '15:00', end: '16:00', day: 'Friday' },
         
         // Baro Deals
         { venue_id: 8, type_of_drink: 'cocktail', category: 'Caipirinha', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
         { venue_id: 8, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Monday' },
         { venue_id: 8, type_of_food: 'appetizer', category: 'Ceviche', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
         { venue_id: 8, type_of_food: 'appetizer', category: 'Churros', price: 6, start: '17:30', end: '20:00', day: 'Monday' },
         { venue_id: 8, type_of_drink: 'cocktail', category: 'Caipirinha', price: 6, start: '16:00', end: '17:30', day: 'Tuesday' },
         { venue_id: 8, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '17:30', end: '20:00', day: 'Tuesday' },
         { venue_id: 8, type_of_food: 'appetizer', category: 'Ceviche', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
         { venue_id: 8, type_of_food: 'appetizer', category: 'Churros', price: 6, start: '17:30', end: '20:00', day: 'Tuesday' },
       
         // The Rec Room Deals
        { venue_id: 9, type_of_drink: 'cocktail', category: 'House Margarita', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 9, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '17:30', end: '20:00', day: 'Monday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Loaded Fries', price: 5, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Chicken Tenders', price: 8, start: '17:30', end: '20:00', day: 'Monday' },
        { venue_id: 9, type_of_drink: 'cocktail', category: 'House Margarita', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 9, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '17:30', end: '20:00', day: 'Tuesday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Loaded Fries', price: 5, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Chicken Tenders', price: 8, start: '17:30', end: '20:00', day: 'Tuesday' },
        { venue_id: 9, type_of_drink: 'cocktail', category: 'House Margarita', price: 7, start: '16:00', end: '17:30', day: 'Wednesday' },
        { venue_id: 9, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '17:30', end: '20:00', day: 'Wednesday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Loaded Fries', price: 5, start: '16:00', end: '17:30', day: 'Wednesday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Chicken Tenders', price: 8, start: '17:30', end: '20:00', day: 'Wednesday' },
        { venue_id: 9, type_of_drink: 'cocktail', category: 'House Margarita', price: 7, start: '16:00', end: '17:30', day: 'Thursday' },
        { venue_id: 9, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '17:30', end: '20:00', day: 'Thursday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Loaded Fries', price: 5, start: '16:00', end: '17:30', day: 'Thursday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Chicken Tenders', price: 8, start: '17:30', end: '20:00', day: 'Thursday' },
        { venue_id: 9, type_of_drink: 'cocktail', category: 'House Margarita', price: 7, start: '16:00', end: '17:30', day: 'Friday' },
        { venue_id: 9, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '17:30', end: '20:00', day: 'Friday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Loaded Fries', price: 5, start: '16:00', end: '17:30', day: 'Friday' },
        { venue_id: 9, type_of_food: 'appetizer', category: 'Chicken Tenders', price: 8, start: '17:30', end: '20:00', day: 'Friday' },

        // Scaddabush Deals
        { venue_id: 10, type_of_drink: 'cocktail', category: 'Bellini', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 10, type_of_drink: 'wine', category: 'House Red Wine', price: 5, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 10, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 10, type_of_drink: 'cocktail', category: 'Bellini', price: 6, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 10, type_of_drink: 'wine', category: 'House Red Wine', price: 5, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 10, type_of_food: 'appetizer', category: 'Bruschetta', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },

        // The Keg Steakhouse + Bar Deals
        { venue_id: 11, type_of_drink: 'cocktail', category: 'Caesar', price: 5, start: '16:30', end: '18:00', day: 'Monday' },
        { venue_id: 11, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '18:00', day: 'Monday' },
        { venue_id: 11, type_of_food: 'main', category: 'Prime Rib Sliders', price: 8, start: '16:30', end: '18:00', day: 'Monday' },
        { venue_id: 11, type_of_food: 'main', category: 'Crispy Shrimp', price: 9, start: '16:30', end: '18:00', day: 'Monday' },
      
            // Bar Chef Deals
            { venue_id: 12, type_of_drink: 'cocktail', category: 'Classic Martini', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
            { venue_id: 12, type_of_drink: 'wine', category: 'Wine by the Glass', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
            { venue_id: 12, type_of_food: 'appetizer', category: 'Gourmet Fries', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
            { venue_id: 12, type_of_food: 'main', category: 'Cheese Board', price: 12, start: '17:00', end: '18:00', day: 'Tuesday' },
            
            // Kōjin Deals
            { venue_id: 13, type_of_drink: 'cocktail', category: 'Whiskey Sour', price: 9, start: '16:00', end: '17:30', day: 'Monday' },
            { venue_id: 13, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
            { venue_id: 13, type_of_food: 'main', category: 'Short Rib Sliders', price: 10, start: '16:00', end: '17:30', day: 'Monday' },
            { venue_id: 13, type_of_food: 'main', category: 'Grilled Veggies', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
            
            // Patria Deals
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Sangria', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Sangria', price: 7, start: '16:00', end: '17:30', day: 'Wednesday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Sangria', price: 7, start: '16:00', end: '17:30', day: 'Thursday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Sangria', price: 7, start: '16:00', end: '17:30', day: 'Friday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Tinto Vermut', price: 5, start: '16:00', end: '17:30', day: 'Tuesday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Tinto Vermut', price: 5, start: '16:00', end: '17:30', day: 'Wednesday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Tinto Vermut', price: 5, start: '16:00', end: '17:30', day: 'Thursday' },
            { venue_id: 14, type_of_drink: 'cocktail', category: 'Tinto Vermut', price: 5, start: '16:00', end: '17:30', day: 'Friday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Patatas Bravas', price: 5, start: '16:00', end: '17:30', day: 'Tuesday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Patatas Bravas', price: 5, start: '16:00', end: '17:30', day: 'Wednesday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Patatas Bravas', price: 5, start: '16:00', end: '17:30', day: 'Thursday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Patatas Bravas', price: 5, start: '16:00', end: '17:30', day: 'Friday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Chorizo Bites', price: 8, start: '16:00', end: '17:30', day: 'Tuesday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Chorizo Bites', price: 8, start: '16:00', end: '17:30', day: 'Wednesday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Chorizo Bites', price: 8, start: '16:00', end: '17:30', day: 'Thursday' },
            { venue_id: 14, type_of_food: 'appetizer', category: 'Chorizo Bites', price: 8, start: '16:00', end: '17:30', day: 'Friday' },
        
        // The Drake Hotel Deals
        { venue_id: 15, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 7, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 15, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 7, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 15, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 7, start: '16:00', end: '17:30', day: 'Wednesday' },
        { venue_id: 15, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 7, start: '16:00', end: '17:30', day: 'Thursday' },
        { venue_id: 15, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 7, start: '16:00', end: '17:30', day: 'Friday' },
        { venue_id: 15, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 15, type_of_food: 'appetizer', category: 'Tater Tots', price: 5, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 15, type_of_food: 'main', category: 'Grilled Cheese', price: 8, start: '16:00', end: '17:30', day: 'Monday' },
        
        // The Queen & Beaver Public House Deals
        { venue_id: 16, type_of_drink: 'beer', category: 'English Ale', price: 6, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 16, type_of_drink: 'beer', category: 'English Ale', price: 6, start: '16:00', end: '17:30', day: 'Tuesday' },
        { venue_id: 16, type_of_drink: 'beer', category: 'English Ale', price: 6, start: '16:00', end: '17:30', day: 'Wednesday' },
        { venue_id: 16, type_of_drink: 'beer', category: 'English Ale', price: 6, start: '16:00', end: '17:30', day: 'Thursday' },
        { venue_id: 16, type_of_drink: 'beer', category: 'English Ale', price: 6, start: '16:00', end: '17:30', day: 'Friday' },
        { venue_id: 16, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 16, type_of_food: 'main', category: 'Fish & Chips', price: 10, start: '16:00', end: '17:30', day: 'Monday' },
        { venue_id: 16, type_of_food: 'appetizer', category: 'Beef Wellington Bites', price: 8, start: '16:00', end: '17:30', day: 'Monday' },
    
              // Wildfire Steakhouse & Wine Bar Deals
              { venue_id: 17, type_of_drink: 'cocktail', category: 'Caipirinha', price: 7, start: '16:30', end: '17:30', day: 'Monday' },
              { venue_id: 17, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:30', end: '17:30', day: 'Monday' },
              { venue_id: 17, type_of_food: 'appetizer', category: 'Oysters', price: 6, start: '16:30', end: '17:30', day: 'Monday' },
              { venue_id: 17, type_of_food: 'main', category: 'Grilled Shrimp Skewers', price: 9, start: '16:30', end: '17:30', day: 'Monday' },
              { venue_id: 17, type_of_drink: 'cocktail', category: 'Caipirinha', price: 7, start: '16:30', end: '17:30', day: 'Tuesday' },
              { venue_id: 17, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:30', end: '17:30', day: 'Tuesday' },
              { venue_id: 17, type_of_food: 'appetizer', category: 'Oysters', price: 6, start: '16:30', end: '17:30', day: 'Tuesday' },
              { venue_id: 17, type_of_food: 'main', category: 'Grilled Shrimp Skewers', price: 9, start: '16:30', end: '17:30', day: 'Tuesday' },
              { venue_id: 17, type_of_drink: 'cocktail', category: 'Caipirinha', price: 7, start: '16:30', end: '17:30', day: 'Wednesday' },
              { venue_id: 17, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:30', end: '17:30', day: 'Wednesday' },
              { venue_id: 17, type_of_food: 'appetizer', category: 'Oysters', price: 6, start: '16:30', end: '17:30', day: 'Wednesday' },
              { venue_id: 17, type_of_food: 'main', category: 'Grilled Shrimp Skewers', price: 9, start: '16:30', end: '17:30', day: 'Wednesday' },
              { venue_id: 17, type_of_drink: 'cocktail', category: 'Caipirinha', price: 7, start: '16:30', end: '17:30', day: 'Thursday' },
              { venue_id: 17, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:30', end: '17:30', day: 'Thursday' },
              { venue_id: 17, type_of_food: 'appetizer', category: 'Oysters', price: 6, start: '16:30', end: '17:30', day: 'Thursday' },
              { venue_id: 17, type_of_food: 'main', category: 'Grilled Shrimp Skewers', price: 9, start: '16:30', end: '17:30', day: 'Thursday' },
              { venue_id: 17, type_of_drink: 'cocktail', category: 'Caipirinha', price: 7, start: '16:30', end: '17:30', day: 'Friday' },
              { venue_id: 17, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:30', end: '17:30', day: 'Friday' },
              { venue_id: 17, type_of_food: 'appetizer', category: 'Oysters', price: 6, start: '16:30', end: '17:30', day: 'Friday' },
              { venue_id: 17, type_of_food: 'main', category: 'Grilled Shrimp Skewers', price: 9, start: '16:30', end: '17:30', day: 'Friday' },
            
        // Richmond Station Deals
        { venue_id: 18, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 8, start: '16:00', end: '17:00', day: 'Monday' },
        { venue_id: 18, type_of_drink: 'beer', category: 'Beer on Tap', price: 5, start: '16:00', end: '17:00', day: 'Monday' },
        { venue_id: 18, type_of_food: 'main', category: 'Grilled Cheese Sandwich', price: 7, start: '16:00', end: '17:00', day: 'Monday' },
        { venue_id: 18, type_of_food: 'appetizer', category: 'Potato Wedges', price: 6, start: '16:00', end: '17:00', day: 'Monday' },
        { venue_id: 18, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 8, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 18, type_of_drink: 'beer', category: 'Beer on Tap', price: 5, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 18, type_of_food: 'main', category: 'Grilled Cheese Sandwich', price: 7, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 18, type_of_food: 'appetizer', category: 'Potato Wedges', price: 6, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 18, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 8, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 18, type_of_drink: 'beer', category: 'Beer on Tap', price: 5, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 18, type_of_food: 'main', category: 'Grilled Cheese Sandwich', price: 7, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 18, type_of_food: 'appetizer', category: 'Potato Wedges', price: 6, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 18, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 8, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 18, type_of_drink: 'beer', category: 'Beer on Tap', price: 5, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 18, type_of_food: 'main', category: 'Grilled Cheese Sandwich', price: 7, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 18, type_of_food: 'appetizer', category: 'Potato Wedges', price: 6, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 18, type_of_drink: 'cocktail', category: 'Gin & Tonic', price: 8, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 18, type_of_drink: 'beer', category: 'Beer on Tap', price: 5, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 18, type_of_food: 'main', category: 'Grilled Cheese Sandwich', price: 7, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 18, type_of_food: 'appetizer', category: 'Potato Wedges', price: 6, start: '16:00', end: '17:00', day: 'Friday' },
    
            // The Miller Tavern Deals
            { venue_id: 19, type_of_drink: 'beer', category: 'House Lager', price: 4, start: '16:00', end: '17:00', day: 'Monday' },
            { venue_id: 19, type_of_drink: 'wine', category: 'White Wine by the Glass', price: 5, start: '16:00', end: '17:00', day: 'Monday' },
            { venue_id: 19, type_of_food: 'appetizer', category: 'Mussels', price: 9, start: '16:00', end: '17:00', day: 'Monday' },
            { venue_id: 19, type_of_food: 'main', category: 'Fried Shrimp', price: 8, start: '16:00', end: '17:00', day: 'Monday' },
            { venue_id: 19, type_of_drink: 'beer', category: 'House Lager', price: 4, start: '16:00', end: '17:00', day: 'Tuesday' },
            { venue_id: 19, type_of_drink: 'wine', category: 'White Wine by the Glass', price: 5, start: '16:00', end: '17:00', day: 'Tuesday' },
            { venue_id: 19, type_of_food: 'appetizer', category: 'Mussels', price: 9, start: '16:00', end: '17:00', day: 'Tuesday' },
            { venue_id: 19, type_of_food: 'main', category: 'Fried Shrimp', price: 8, start: '16:00', end: '17:00', day: 'Tuesday' },
            { venue_id: 19, type_of_drink: 'beer', category: 'House Lager', price: 4, start: '16:00', end: '17:00', day: 'Wednesday' },
            { venue_id: 19, type_of_drink: 'wine', category: 'White Wine by the Glass', price: 5, start: '16:00', end: '17:00', day: 'Wednesday' },
            { venue_id: 19, type_of_food: 'appetizer', category: 'Mussels', price: 9, start: '16:00', end: '17:00', day: 'Wednesday' },
            { venue_id: 19, type_of_food: 'main', category: 'Fried Shrimp', price: 8, start: '16:00', end: '17:00', day: 'Wednesday' },
            { venue_id: 19, type_of_drink: 'beer', category: 'House Lager', price: 4, start: '16:00', end: '17:00', day: 'Thursday' },
            { venue_id: 19, type_of_drink: 'wine', category: 'White Wine by the Glass', price: 5, start: '16:00', end: '17:00', day: 'Thursday' },
            { venue_id: 19, type_of_food: 'appetizer', category: 'Mussels', price: 9, start: '16:00', end: '17:00', day: 'Thursday' },
            { venue_id: 19, type_of_food: 'main', category: 'Fried Shrimp', price: 8, start: '16:00', end: '17:00', day: 'Thursday' },
            { venue_id: 19, type_of_drink: 'beer', category: 'House Lager', price: 4, start: '16:00', end: '17:00', day: 'Friday' },
            { venue_id: 19, type_of_drink: 'wine', category: 'White Wine by the Glass', price: 5, start: '16:00', end: '17:00', day: 'Friday' },
            { venue_id: 19, type_of_food: 'appetizer', category: 'Mussels', price: 9, start: '16:00', end: '17:00', day: 'Friday' },
            { venue_id: 19, type_of_food: 'main', category: 'Fried Shrimp', price: 8, start: '16:00', end: '17:00', day: 'Friday' },
          
           // Bar Reyna Deals
           { venue_id: 20, type_of_drink: 'cocktail', category: 'House Sangria', price: 7, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'House Sangria', price: 7, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'House Sangria', price: 7, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'House Sangria', price: 7, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'House Sangria', price: 7, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'Mojito', price: 8, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'Mojito', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'Mojito', price: 8, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'Mojito', price: 8, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 20, type_of_drink: 'cocktail', category: 'Mojito', price: 8, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Tacos (3)', price: 10, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Tacos (3)', price: 10, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Tacos (3)', price: 10, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Tacos (3)', price: 10, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Tacos (3)', price: 10, start: '17:00', end: '18:00', day: 'Friday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Bruschetta', price: 6, start: '17:00', end: '18:00', day: 'Monday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Bruschetta', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Bruschetta', price: 6, start: '17:00', end: '18:00', day: 'Wednesday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Bruschetta', price: 6, start: '17:00', end: '18:00', day: 'Thursday' },
           { venue_id: 20, type_of_food: 'appetizer', category: 'Bruschetta', price: 6, start: '17:00', end: '18:00', day: 'Friday' },
        
            // The Saint Tavern Deals
        { venue_id: 21, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:30', end: '17:30', day: 'Monday' },
        { venue_id: 21, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:30', end: '17:30', day: 'Tuesday' },
        { venue_id: 21, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:30', end: '17:30', day: 'Wednesday' },
        { venue_id: 21, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:30', end: '17:30', day: 'Thursday' },
        { venue_id: 21, type_of_drink: 'wine', category: 'House Wine', price: 5, start: '16:30', end: '17:30', day: 'Friday' },
        { venue_id: 21, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '17:30', day: 'Monday' },
        { venue_id: 21, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '17:30', day: 'Tuesday' },
        { venue_id: 21, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '17:30', day: 'Wednesday' },
        { venue_id: 21, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '17:30', day: 'Thursday' },
        { venue_id: 21, type_of_drink: 'beer', category: 'Domestic Beer', price: 4, start: '16:30', end: '17:30', day: 'Friday' },
        { venue_id: 21, type_of_food: 'appetizer', category: 'Chicken Wings', price: 8, start: '16:30', end: '17:30', day: 'Monday' },
        { venue_id: 21, type_of_food: 'appetizer', category: 'Chicken Wings', price: 8, start: '16:30', end: '17:30', day: 'Tuesday' },
        { venue_id: 21, type_of_food: 'appetizer', category: 'Chicken Wings', price: 8, start: '16:30', end: '17:30', day: 'Wednesday' },
        { venue_id: 21, type_of_food: 'appetizer', category: 'Chicken Wings', price: 8, start: '16:30', end: '17:30', day: 'Thursday' },
        { venue_id: 21, type_of_food: 'appetizer', category: 'Chicken Wings', price: 8, start: '16:30', end: '17:30', day: 'Friday' },
        { venue_id: 21, type_of_food: 'main', category: 'Poutine', price: 7, start: '17:30', end: '18:30', day: 'Monday' },
        { venue_id: 21, type_of_food: 'main', category: 'Poutine', price: 7, start: '17:30', end: '18:30', day: 'Tuesday' },
        { venue_id: 21, type_of_food: 'main', category: 'Poutine', price: 7, start: '17:30', end: '18:30', day: 'Wednesday' },
        { venue_id: 21, type_of_food: 'main', category: 'Poutine', price: 7, start: '17:30', end: '18:30', day: 'Thursday' },
        { venue_id: 21, type_of_food: 'main', category: 'Poutine', price: 7, start: '17:30', end: '18:30', day: 'Friday' },
      
        // Taverna Mercatto Deals
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Aperol Spritz', price: 7, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Aperol Spritz', price: 7, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Aperol Spritz', price: 7, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Aperol Spritz', price: 7, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Prosecco', price: 8, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Prosecco', price: 8, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Prosecco', price: 8, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 22, type_of_drink: 'cocktail', category: 'Prosecco', price: 8, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 22, type_of_food: 'main', category: 'Margherita Pizza', price: 9, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 22, type_of_food: 'main', category: 'Margherita Pizza', price: 9, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 22, type_of_food: 'main', category: 'Margherita Pizza', price: 9, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 22, type_of_food: 'main', category: 'Margherita Pizza', price: 9, start: '16:00', end: '17:00', day: 'Friday' },
        { venue_id: 22, type_of_food: 'main', category: 'Fried Calamari', price: 10, start: '16:00', end: '17:00', day: 'Tuesday' },
        { venue_id: 22, type_of_food: 'main', category: 'Fried Calamari', price: 10, start: '16:00', end: '17:00', day: 'Wednesday' },
        { venue_id: 22, type_of_food: 'main', category: 'Fried Calamari', price: 10, start: '16:00', end: '17:00', day: 'Thursday' },
        { venue_id: 22, type_of_food: 'main', category: 'Fried Calamari', price: 10, start: '16:00', end: '17:00', day: 'Friday' }, 
        
          // Café Boulud Deals 
          { venue_id: 23, type_of_drink: 'wine', category: 'Red Wine by the Glass', price: 7, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 23, type_of_drink: 'wine', category: 'Red Wine by the Glass', price: 7, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 23, type_of_drink: 'wine', category: 'Red Wine by the Glass', price: 7, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 23, type_of_drink: 'wine', category: 'Red Wine by the Glass', price: 7, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 23, type_of_drink: 'cocktail', category: 'Classic Martini', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 23, type_of_drink: 'cocktail', category: 'Classic Martini', price: 8, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 23, type_of_drink: 'cocktail', category: 'Classic Martini', price: 8, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 23, type_of_drink: 'cocktail', category: 'Classic Martini', price: 8, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 23, type_of_food: 'appetizer', category: 'Duck Pâté', price: 9, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 23, type_of_food: 'appetizer', category: 'Duck Pâté', price: 9, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 23, type_of_food: 'appetizer', category: 'Duck Pâté', price: 9, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 23, type_of_food: 'appetizer', category: 'Duck Pâté', price: 9, start: '17:00', end: '18:00', day: 'Friday' },
          { venue_id: 23, type_of_food: 'main', category: 'Charcuterie Plate', price: 12, start: '17:00', end: '18:00', day: 'Tuesday' },
          { venue_id: 23, type_of_food: 'main', category: 'Charcuterie Plate', price: 12, start: '17:00', end: '18:00', day: 'Wednesday' },
          { venue_id: 23, type_of_food: 'main', category: 'Charcuterie Plate', price: 12, start: '17:00', end: '18:00', day: 'Thursday' },
          { venue_id: 23, type_of_food: 'main', category: 'Charcuterie Plate', price: 12, start: '17:00', end: '18:00', day: 'Friday' },
        
            // KINKA IZAKAYA ORIGINAL Deals
        { venue_id: 24, type_of_drink: 'beer', category: 'Sapporo Beer', price: 5, start: '17:00', end: '18:00', day: 'Monday' },
        { venue_id: 24, type_of_drink: 'beer', category: 'Sapporo Beer', price: 5, start: '17:00', end: '18:00', day: 'Tuesday' },
        { venue_id: 24, type_of_drink: 'beer', category: 'Sapporo Beer', price: 5, start: '17:00', end: '18:00', day: 'Wednesday' },
        { venue_id: 24, type_of_drink: 'beer', category: 'Sapporo Beer', price: 5, start: '17:00', end: '18:00', day: 'Thursday' },
        { venue_id: 24, type_of_drink: 'cocktail', category: 'Highball', price: 6, start: '17:00', end: '18:00', day: 'Monday' },
        { venue_id: 24, type_of_drink: 'cocktail', category: 'Highball', price: 6, start: '17:00', end: '18:00', day: 'Tuesday' },
        { venue_id: 24, type_of_drink: 'cocktail', category: 'Highball', price: 6, start: '17:00', end: '18:00', day: 'Wednesday' },
        { venue_id: 24, type_of_drink: 'cocktail', category: 'Highball', price: 6, start: '17:00', end: '18:00', day: 'Thursday' },
        { venue_id: 24, type_of_food: 'appetizer', category: 'Karaage Chicken', price: 7, start: '17:00', end: '18:00', day: 'Monday' },
        { venue_id: 24, type_of_food: 'appetizer', category: 'Karaage Chicken', price: 7, start: '17:00', end: '18:00', day: 'Tuesday' },
        { venue_id: 24, type_of_food: 'appetizer', category: 'Karaage Chicken', price: 7, start: '17:00', end: '18:00', day: 'Wednesday' },
        { venue_id: 24, type_of_food: 'appetizer', category: 'Karaage Chicken', price: 7, start: '17:00', end: '18:00', day: 'Thursday' },
        { venue_id: 24, type_of_food: 'main', category: 'Prawn Tempura', price: 8, start: '17:00', end: '18:00', day: 'Monday' },
        { venue_id: 24, type_of_food: 'main', category: 'Prawn Tempura', price: 8, start: '17:00', end: '18:00', day: 'Tuesday' },
        { venue_id: 24, type_of_food: 'main', category: 'Prawn Tempura', price: 8, start: '17:00', end: '18:00', day: 'Wednesday' },
        { venue_id: 24, type_of_food: 'main', category: 'Prawn Tempura', price: 8, start: '17:00', end: '18:00', day: 'Thursday' },
      
         // Tutto Pronto Deals
         { venue_id: 25, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:00', day: 'Monday' },
         { venue_id: 25, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:00', day: 'Tuesday' },
         { venue_id: 25, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:00', day: 'Wednesday' },
         { venue_id: 25, type_of_drink: 'wine', category: 'House Red Wine', price: 6, start: '16:00', end: '17:00', day: 'Thursday' },
         { venue_id: 25, type_of_drink: 'cocktail', category: 'Classic Negroni', price: 8, start: '16:00', end: '17:00', day: 'Monday' },
         { venue_id: 25, type_of_drink: 'cocktail', category: 'Classic Negroni', price: 8, start: '16:00', end: '17:00', day: 'Tuesday' },
         { venue_id: 25, type_of_drink: 'cocktail', category: 'Classic Negroni', price: 8, start: '16:00', end: '17:00', day: 'Wednesday' },
         { venue_id: 25, type_of_drink: 'cocktail', category: 'Classic Negroni', price: 8, start: '16:00', end: '17:00', day: 'Thursday' },
         { venue_id: 25, type_of_food: 'appetizer', category: 'Frittata', price: 7, start: '16:00', end: '17:00', day: 'Monday' },
         { venue_id: 25, type_of_food: 'appetizer', category: 'Frittata', price: 7, start: '16:00', end: '17:00', day: 'Tuesday' },
         { venue_id: 25, type_of_food: 'appetizer', category: 'Frittata', price: 7, start: '16:00', end: '17:00', day: 'Wednesday' },
         { venue_id: 25, type_of_food: 'appetizer', category: 'Frittata', price: 7, start: '16:00', end: '17:00', day: 'Thursday' },
         { venue_id: 25, type_of_food: 'main', category: 'Antipasto', price: 9, start: '16:00', end: '17:00', day: 'Monday' },
         { venue_id: 25, type_of_food: 'main', category: 'Antipasto', price: 9, start: '16:00', end: '17:00', day: 'Tuesday' },
         { venue_id: 25, type_of_food: 'main', category: 'Antipasto', price: 9, start: '16:00', end: '17:00', day: 'Wednesday' },
         { venue_id: 25, type_of_food: 'main', category: 'Antipasto', price: 9, start: '16:00', end: '17:00', day: 'Thursday' }
       
        ]);
      });
  }